#!/bin/sh
docker rmi clefos/ade
docker rmi clefos/ansible
docker rmi clefos/bacula-db
docker rmi clefos/bacula-db-data
docker rmi clefos/bacula-dir
docker rmi clefos/bacula-fd
docker rmi clefos/bacula-sd
docker rmi clefos/bind
docker rmi clefos/glibc-test
docker rmi clefos/cobol
docker rmi clefos/compose-ui
docker rmi clefos/couchdb
docker rmi clefos/django
docker rmi clefos/visualizer
docker rmi clefos/earthquake
docker rmi clefos/erlang
docker rmi clefos/etcd
docker rmi clefos/fluentd
docker rmi clefos/golang
docker rmi grafana
docker rmi clefos/hadoop
docker rmi clefos/hello-nodejs
docker rmi clefos/httpd
docker rmi docker.io/clefos/ibmjava:8
docker rmi docker.io/clefos/ibmjava:8-sdk
docker rmi docker.io/clefos/maven:8
docker rmi docker.io/clefos/maven:11
docker rmi docker.io/clefos/ibmjava:11-sdk
docker rmi docker.io/clefos/ibmjava:8-sfj
docker rmi clefos/ibmjava:8-sdk
docker rmi clefos/ibmjava:8-sfj
docker rmi clefos/ibmjava:11-sdk
docker rmi clefos/maven:8
docker rmi clefos/maven:11
docker rmi clefos/jboss-wildfly
docker rmi clefos/jupyter
docker rmi clefos/kubernetes
docker rmi clefos/lighttpd
docker rmi clefos/mariadb
docker rmi clefos/mean
docker rmi clefos/meanjs
docker rmi clefos/mediawiki
docker rmi clefos/memcached
docker rmi clefos/mongodb
docker rmi clefos/mono
docker rmi clefos/nginx
docker rmi clefos/node:8
docker rmi clefos/node:10
docker rmi clefos/node:12
docker rmi clefos/openjdk:8
docker rmi clefos/openjdk:11
docker rmi clefos/openjdk:12
docker rmi docker.io/clefos/spark
docker rmi docker.io/clefos/zeppelin
docker rmi clefos/owncloud
docker rmi clefos/postgresql
docker rmi clefos/puppet
docker rmi clefos/qpid
docker rmi clefos/r-base
docker rmi clefos/rabbitmq
docker rmi react-client
docker rmi react-api
docker rmi clefos/redis
docker rmi clefos/registry
docker rmi clefos/saltmaster
docker rmi clefos/solr
docker rmi clefos/spark-sa
docker rmi clefos/spark-ui-proxy
docker rmi clefos/ssh
docker rmi clefos/swarm
docker rmi clefos/systemd
docker rmi clefos/tomcat
docker rmi clefos/tools
docker rmi clefos/ulboracms
docker rmi clefos/watchtower
docker rmi clefos/wordpress
docker rmi clefos/wordpress-sa
rm openshift-spark/spark/zeppelin/lucene-core-5.3.2.jar
rm hadoop-openshift/hadoop-3.1.0.tar.gz
rm hadoop-openshift/hadoop-2.8.1.tar.gz