#
# Derived from the RedCoolBeans project Dockerfile
#
FROM 		brunswickheads/postgresql-9.2.13-s390x:latest

MAINTAINER 	"The ClefOS Project" <neale@sinenomine.net>
LABEL 		com.baculasystems.bacula.version="5.2.13"
