FROM 		clefos/clefos:clefos7

MAINTAINER	"The ClefOS Project" <neale@sinenomine.net>
LABEL 		Vendor="ClefOS" License="GPLv2"

ADD		watchtower /usr/bin

VOLUME 		/var/run/docker.sock 

CMD 		["watchtower"]
