#!/bin/sh
VOLUME='-v /tmp/mariadb:/var/lib/mysql:Z'
DATABASE=mydb
USER=myuser
PASSWORD=password
ROOTPASS=rootpass
docker run -d                   		\
    -e MYSQL_USER=$USER              		\
    -e MYSQL_PASSWORD=$PASSWORD      		\
    -e MYSQL_DATABASE=$DATABASE      		\
    -e MYSQL_ROOT_PASSWORD=$ROOTPASS 		\
    $VOLUME --name=mariadb sinenomine/mariadb-s390x

docker run --link=mariadb:db -d 		\
	--name wordpress -p 8080:80 sinenomine/wordpress-s390x
