#!/bin/bash

# Copyright 2015 The Kubernetes Authors All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. /start-common.sh

MASTER="spark://${APPLICATION_NAME}-master.${APPLICATION_NAMESPACE}.svc.cluster.local:7077"

# Run spark-class directly so that when it exits (or crashes), the pod restarts.
spark-class org.apache.spark.deploy.worker.Worker ${MASTER} --webui-port 8081

exit

MASTER_IP=""

while [ -z "${MASTER_IP}" ]
do
	echo *************************
	MASTER_IP=`curl -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" -k -XGET "https://openshift.default.svc.cluster.local/api/v1/namespaces/${POD_NAMESPACE}/pods?labelSelector=name=${APPLICATION_NAME}-master" | grep podIP | sed -e 's/.*"podIP": "\(.*\)".*/\1/'`
	echo MASTER ${MASTER_IP}
	echo *************************
	if [ -z "${MASTER_IP}" ]; then
		sleep 5s
	fi
done

MASTER="spark://${MASTER_IP}:7077"

# Run spark-class directly so that when it exits (or crashes), the pod restarts.
spark-class org.apache.spark.deploy.worker.Worker ${MASTER} --webui-port 8081
